// <auto-generated />
namespace App.Game.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inicial1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicial1));
        
        string IMigrationMetadata.Id
        {
            get { return "201803251131487_inicial1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
